services:
    front-end:
        build: .
        ports:
            - '8888:8888'
        volumes:
            - .:/app
        command: python manage.py runserver 0.0.0.0:8888

    auth_database:
        volumes:
            - auth_service:/var/lib/mysql
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: password #
            MYSQL_DATABASE: auth
            MYSQL_USER: user_testdb
            MYSQL_PASSWORD: password
        ports:
            - 3306:3307
        networks:
            - quiz-lab

    quiz_database:
        volumes:
            - quiz_service:/var/lib/mysql
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: password #
            MYSQL_DATABASE: quiz
            MYSQL_USER: user_testdb
            MYSQL_PASSWORD: password
        ports:
            - 3306:3308

    redis:
        image: redis:latest
        ports:
            - 6379:6379
        networks:
            - quiz-lab

    axonserver:
        image: axoniq/axonserver
        ports:
            - 8024:8024
            - 8124:8124
        hostname: axonserver
        environment:
            AXONSERVER_DEVMODE_ENABLED: 'true'
        networks:
            - quiz-lab

    discoveryServer:
        image: 'discovery_server1:latest'
        ports:
            - '8761:8762'
        networks:
            - quiz-lab

    api_gateway:
        image: 'api_gateway:latest'
        ports:
            - '0:9000'
        environment:
            - eureka.client.service-url.defaultZone:http://discovery_server:8761/eureka
        networks:
            - quiz-lab

    auth:
        image: 'auth:latest'
        ports:
            - '0:9003'
        environment:
            eureka.client.service-url.defaultZone: http://discoveryServer:8761/eureka
            spring.datasource.url: jdbc:mysql://auth_database:3306/auth #luu y la phai ket noi toi port trong container
            spring.datasource.username: root
            spring.datasource.password: password
            SPRING_REDIS_HOST: redis
            SPRING_REDIS_PORT: 6379
            axon.axonserver.servers: axonserver:8124
            AXON_SERVER_PORT: 8124
        networks:
            - quiz-lab


    notification:
        image: 'notification:latest'
        ports:
            - '9004:0'
        environment:
            eureka.client.service-url.defaultZone: http://discovery_server:8761/eureka\
            SPRING_REDIS_HOST: redis
            SPRING_REDIS_PORT: 6379
            axon.axonserver.servers: axonserver:8124
            AXON_SERVER_PORT: 8124
        networks:
            - quiz-lab

    quiz:
        image: 'quiz:latest'
        ports:
            - '9005:0'
        environment:
            eureka.client.service-url.defaultZone: http://discovery_server:8761/eureka
            spring.datasource.url: jdbc:mysql://quiz_database:3306/auth
            axon.axonserver.servers: axonserver:8124
            AXON_SERVER_PORT: 8124
        networks:
            - quiz-lab

    create_quiz:
        image: 'create_quiz:latest'
        ports:
            - '9006:0'
        environment:
            eureka.client.service-url.defaultZone: http://discovery_server:8761/eureka
            axon.axonserver.servers: axonserver:8124
            AXON_SERVER_PORT: 8124
            front-end.url: http://front-end
        networks:
            - quiz-lab

volumes:
    auth_service:
        external: true
    quiz_service:
        external: true

networks:
    quiz-lab:
        driver: bridge