spring:
    data:
        redis:
            host: localhost
            port: 6379

    application.name: quiz-service
    datasource:
        url: jdbc:mysql://localhost:3306/quiz
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

    instance:
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 5
        hostname: localhost

server:
    port: 9003

axon:
    axonserver:
        mode: command
        event:
            processor:
                default:
                    tracking: true
                    source: AxonServer
                    mode: tracking
                    event-processor-mode: tracking
                    retry:
                        delay: 5000
                        max-attempts: 50
                    transaction-timeout: PT5M
                    rollback-on-exception: true