spring:
    application:
        name: notification

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

    instance:
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 5
        hostname: localhost

server:
    port: 0

axon:
    axonserver:
        mode: command
        event:
            processor:
                default:
                    tracking: true
                    source: AxonServer
                    mode: tracking
                    event-processor-mode: tracking
                    retry:
                        delay: 5000
                        max-attempts: 50
                    transaction-timeout: PT5M
                    rollback-on-exception: true