spring:
    application:
        name: api_gateway

    cloud:
        gateway:
            routes:
                - id: quiz-service
                  uri: lb://quiz-service
                  predicates:
                      - Path=/api/v1/quiz/**

                - id: auth-service
                  uri: lb://auth-service
                  predicates:
                    - Path=/api/v1/auth/**
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
server:
    port: 9000