spring:
    application:
        name: api_gateway

    cloud:
        gateway:
            routes:
                - id: auth-service
                  uri: lb://auth-service
                  predicates:
                    - Path=/api/v1/auth/**

                - id: quiz-service
                  uri: lb://quiz-service
                  predicates:
                    - Path=/api/v1/quiz/**

                - id: create-quiz
                  uri: lb://create-quiz
                  predicates:
                    - Path=/api/v1/create-quiz/**

            default-filters:
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
            globalcors:
                cors-configurations:
                    '[/**]':
                        allowedOrigins: "*"
                        allowedHeaders: "*"
                        allowedMethods:
                            - GET
                            - POST


eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
server:
    port: 9000