spring:
    application:
        name: create-quiz

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

    instance:
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 5
        hostname: localhost

server:
    port: 0